### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jodjo86** [angelovangel/nanotimes#1]
Hello,

Your tool is very useful for me and I think it would be interesting to add its functionality to the Chopper tool (1). I made the proposal to the author (2). As you do not have a license, I would like to validate with you if it is possible to use your code.

Thanks,

1- https://github.com/wdecoster/chopper
2- https://github.com/wdecoster/chopper/issues/2

**Comment by angelovangel** [comment]
Hi,
thank you for reaching out, I have added a license. Have you tried [faster](https://github.com/angelovangel/faster)?

**Comment by jodjo86** [comment]
wow! I just tried it. Thanks for sharing your work.
