### ISSUE TITLE
Filter for a certain coverage (amount of sequenced bases) and extract/report time taken

### ISSUE THREAD

**Issue by gwl2** [angelovangel/nanotimes#2]
Great tool.
There are sometimes analysis where I'd like to get a certain coverage and also get the information when this coverage was achived for a certain barcode. 
Would it also be possible to add an option that the user defines a certain number of bases (e.g. 400 megabasepairs) and nanotime filters the reads from start to the time point when the number of bases were sequenced plus an output of the end time (when the number of bases criterion was met)?

**Comment by angelovangel** [comment]
Hi @gwl2 ,
`nanotimes` reads just the timestamps. I can imagine you can accomplish this by combining it with other tools like [seqkit](https://github.com/shenwei356/seqkit) or [faster](https://github.com/angelovangel/faster)...
